export type FlowerCategory = "imported" | "tropical" | "local";

export interface FlowerType {
  id: string;
  name_en: string;
  name_si: string;
  localName?: string;
  imageUrl: string;
  defaultUnit: "stem" | "bunch" | "arrangement" | "item";
  category: FlowerCategory;
}

function img(id: string): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=320&h=240&q=75`;
}

export const FLOWER_CATALOG: FlowerType[] = [
  {
    id: "rose",
    name_en: "Rose",
    name_si: "රෝස",
    imageUrl: img("1548199973-03664775a2f9"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "gerbera",
    name_en: "Gerbera",
    name_si: "ජර්බෙරා",
    imageUrl: img("1527529482837-4698179dc6ce"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "chrysanthemum",
    name_en: "Chrysanthemum",
    name_si: "ක්‍රිසෑන්තිමම්",
    imageUrl: img("1604174184911-b6789609f96b"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "carnation",
    name_en: "Carnation",
    name_si: "කාර්නේෂන්",
    imageUrl: img("1617197618590-ff7c5bdb5ec0"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "orchid",
    name_en: "Orchid",
    name_si: "ඕකිඩ්",
    imageUrl: img("1566843972142-a7fcb70de055"),
    defaultUnit: "stem",
    category: "tropical",
  },
  {
    id: "lily",
    name_en: "Lily",
    name_si: "ලිලී",
    imageUrl: img("1583863788434-e58a36330cf0"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "alstroemeria",
    name_en: "Alstroemeria",
    name_si: "ඇස්ටොමාරිය",
    localName: "Astomariya",
    imageUrl: img("1510172951498-87b7fb5f5a8c"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "michaelmas-daisy",
    name_en: "Michael Daisy",
    name_si: "මිකේල් ඩේසි",
    localName: "Michaelmas Daisy",
    imageUrl: img("1504208434309-cb69f4fe52b0"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "super-daisy",
    name_en: "Super Daisy",
    name_si: "සුපර් ඩේසි",
    imageUrl: img("1477265977826-73c59e48f82e"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "macrum-daisy",
    name_en: "Macrum Daisy",
    name_si: "මැක්‍රම් ඩේසි",
    imageUrl: img("1490750967868-88d33a4f2dce"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "babys-breath",
    name_en: "Baby's Breath",
    name_si: "බේබිස් බ්‍රෙත්",
    imageUrl: img("1508739773434-c26b3d09e071"),
    defaultUnit: "bunch",
    category: "imported",
  },
  {
    id: "statice",
    name_en: "Statice",
    name_si: "ස්ටැටිස්",
    localName: "Limonium",
    imageUrl: img("1512099256965-bc82ca03a528"),
    defaultUnit: "bunch",
    category: "imported",
  },
  {
    id: "goldenrod",
    name_en: "Goldenrod",
    name_si: "ගෝල්ඩ්නරොඩ්",
    localName: "Solidago",
    imageUrl: img("1567016432779-094069958ea5"),
    defaultUnit: "bunch",
    category: "imported",
  },
  {
    id: "gladiolus",
    name_en: "Gladiolus",
    name_si: "ග්ලැඩියෝලස්",
    imageUrl: img("1551845041-abe6e4027745"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "hydrangea",
    name_en: "Hydrangea",
    name_si: "හයිඩ්‍රේන්ජියා",
    imageUrl: img("1574684891174-df6b02ab38d7"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "snapdragon",
    name_en: "Snapdragon",
    name_si: "ස්නෑප්ඩ්‍රැගන්",
    imageUrl: img("1592409561738-78dda3ddc70d"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "china-aster",
    name_en: "China Aster",
    name_si: "චයිනා ඇස්ටර්",
    imageUrl: img("1416879595882-3373a0480b5b"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "star-of-bethlehem",
    name_en: "Star of Bethlehem",
    name_si: "ස්ටාර් ඔෆ් බෙත්ලෙහෙම්",
    imageUrl: img("1528360983277-13d401cdc186"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "anthurium",
    name_en: "Anthurium",
    name_si: "ඇන්තූරියම්",
    imageUrl: img("1561018928-bfff7be8a8a5"),
    defaultUnit: "stem",
    category: "tropical",
  },
  {
    id: "calla-lily",
    name_en: "Arum / Calla Lily",
    name_si: "ආරම් / කල්ලා ලිලී",
    imageUrl: img("1585128792050-3af2f43a9e0e"),
    defaultUnit: "stem",
    category: "imported",
  },
  {
    id: "heliconia",
    name_en: "Heliconia",
    name_si: "හෙලිකෝනියා",
    localName: "Crab Claw",
    imageUrl: img("1558618666-fcd25c85cd64"),
    defaultUnit: "stem",
    category: "tropical",
  },
  {
    id: "ginger-flower",
    name_en: "Ginger Flower",
    name_si: "ඉඟුරු මල",
    imageUrl: img("1559825481-12a05cc00344"),
    defaultUnit: "stem",
    category: "tropical",
  },
  {
    id: "lotus",
    name_en: "Lotus",
    name_si: "නෙළුම්",
    localName: "Nelum",
    imageUrl: img("1555216204-9985a6fc4e8d"),
    defaultUnit: "stem",
    category: "local",
  },
  {
    id: "blue-water-lily",
    name_en: "Blue Water Lily",
    name_si: "නිල් මානෙල්",
    localName: "Nil Manel",
    imageUrl: img("1535572290543-960a8046f5af"),
    defaultUnit: "stem",
    category: "local",
  },
  {
    id: "white-water-lily",
    name_en: "White Water Lily",
    name_si: "ඔළු",
    localName: "Olu",
    imageUrl: img("1575383991048-05d5cc2cb3a4"),
    defaultUnit: "stem",
    category: "local",
  },
  {
    id: "jasmine",
    name_en: "Jasmine",
    name_si: "පිච්ච",
    localName: "Pichcha / Saman Pichcha",
    imageUrl: img("1583792580485-1bcf5c0b4b9c"),
    defaultUnit: "bunch",
    category: "local",
  },
  {
    id: "frangipani",
    name_en: "Frangipani",
    name_si: "අරලිය",
    localName: "Araliya",
    imageUrl: img("1559181567-c3190100d15a"),
    defaultUnit: "item",
    category: "local",
  },
  {
    id: "marigold",
    name_en: "Marigold",
    name_si: "දාස් පෙතිය",
    localName: "Das Pethiya",
    imageUrl: img("1564490359426-a26e7a5e50e2"),
    defaultUnit: "bunch",
    category: "local",
  },
];
